verboseLogging: false
port: 7001
URL: "http://localhost:7001/"
postConfigResponse: 'postHopperConfig'
initialPageResponse: 'HopperConfig'
editPageResponse: 'editHopperConfig'
postEditPageResponse: 'postEditHopperConfig'
maxInputItems: 100
disabledItems:
    - 'spawn_egg'