port: 7000
URL: "http://localhost:7000/"
postConfigResponse: 'postHopperConfig'
initialPageResponse: 'HopperConfig'
editPageResponse: 'editHopperConfig'
postEditPageResponse: 'postEditHopperConfig'
maxInputItems: 100