name: ItemSorter
main: tollenaar.stephen.ItemSorter.Core.ItemSorter
version: 6.4
authors: [guitargun]
loadbefore: [Storefront]
description: able to sort items in a better way using hoppers
api-version: 1.18
commands: 
     ItemSorter:
             description: various commands exists with this plugin
             usage: /<command>